# Generated by Django 6.0.7 on 2026-07-28 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchroster',
            name='match',
            field=models.ForeignKey(db_column='match_id', on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='api.match'),
        ),
        migrations.AlterField(
            model_name='matchroster',
            name='player',
            field=models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, related_name='match_rosters', to='api.player'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['-date'], name='matches_date_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['match_type'], name='matches_type_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['team_a', 'team_b'], name='matches_teams_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['match_type', '-date'], name='matches_type_date_idx'),
        ),
        migrations.AddIndex(
            model_name='matchroster',
            index=models.Index(fields=['match', 'team_name'], name='roster_match_team_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['name'], name='players_name_idx'),
        ),
    ]
