# Generated by Django 6.0.7 on 2026-07-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_matchroster_match_alter_matchroster_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['gender'], name='matches_gender_idx'),
        ),
    ]
